name: Deploy FastAPI Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.SERVER_IP }}
          USER_NAME: ${{ secrets.SERVER_USER }}
        run: |
          echo "$PRIVATE_KEY" > privatekey.pem
          chmod 600 privatekey.pem

          trap "rm -f privatekey.pem" EXIT

          ssh -o StrictHostKeyChecking=no -i privatekey.pem ${USER_NAME}@${HOST_NAME} << 'EOF'
            cd ~/fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
            sudo systemctl restart fastapi
            sudo systemctl restart nginx
          EOF
