name: Deploy FastAPI Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH Key and Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          # Save the private key securely
          echo "$PRIVATE_KEY" | tr -d '\r' > privatekey.pem
          chmod 600 privatekey.pem

          # Test SSH Connection Before Deployment
          ssh -o StrictHostKeyChecking=no -i privatekey.pem ${USER_NAME}@${HOST_NAME} "echo '✅ SSH Connected Successfully'"

          # Deploying the FastAPI app
          ssh -o StrictHostKeyChecking=no -i privatekey.pem ${USER_NAME}@${HOST_NAME} << 'EOF'
            cd ~/fastapi-book-project

            # Fetch latest changes and hard reset to match remote branch
            git fetch origin main
            git reset --hard origin/main

            source venv/bin/activate
            pip install -r requirements.txt
            sudo service fastapi restart
            sudo service nginx restart

            # Wait for FastAPI to start properly
            sleep 5

            # Check if /stage2 endpoint returns 200 OK
            RESPONSE=\$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/stage2)
            if [ "\$RESPONSE" -ne 200 ]; then
                echo "❌ Stage2 endpoint failed! Got HTTP \$RESPONSE"
                exit 1
            fi
            echo "✅ Stage2 endpoint is working correctly!"
          EOF
