name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt update
          sudo apt install -y docker-ce docker-ce-cli containerd.io

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t adenijifisayo740/fastapi-app .
          docker push adenijifisayo740/fastapi-app

      - name: Deploy to server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Ensure dependencies are up-to-date
            sudo apt update -y
            sudo apt install -y docker-ce docker-ce-cli containerd.io

            # Pull latest changes from GitHub
            cd /home/${{ secrets.SERVER_USER }}/myfastapi-book-project
            git fetch origin main
            git reset --hard origin/main

            # Pull the latest Docker image
            docker pull adenijifisayo740/fastapi-app:latest

            # Stop and remove old container if it exists
            docker stop fastapi-app || true
            docker rm fastapi-app || true

            # Run the new container
            docker run -d -p 8000:8000 --name fastapi-app adenijifisayo740/fastapi-app:latest
          EOF
          rm -f private_key
