      - name: Deploy application
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@13.244.107.173 << 'EOF'
          cd ~/fastapi-book-project
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi
          sudo systemctl is-active --quiet fastapi || (echo "FastAPI service failed to start!" && exit 1)
          
          # Wait for FastAPI to fully restart
          sleep 5

          # Check if /stage2 endpoint is returning 200
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/stage2)
          if [ "$RESPONSE" -ne 200 ]; then
              echo "❌ Stage 2 endpoint is not returning 200 OK (Got $RESPONSE)"
              exit 1
          fi
          echo "✅ Stage 2 endpoint is active and returning 200 OK!"
          EOF
