name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Deploy to AWS Server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            # Change to the project directory (if exists), otherwise clone it
            cd /home/ubuntu || git clone https://github.com/adenijifisayo/fastapi-book-project.git && cd fastapi-book-project
            git fetch origin main
            git reset --hard origin/main

            # Stop and remove existing container
            docker stop fastapi-app || true
            docker rm fastapi-app || true

            # Pull latest Docker image
            docker pull adenijifisayo740/fastapi-app:latest

            # Run new container
            docker run -d -p 8000:8000 --name fastapi-app adenijifisayo740/fastapi-app:latest
          EOF
          
          # Clean up SSH key
          rm -f private_key
